#!/usr/bin/env php
<?php

$phar = new Phar('pip.phar', 0, 'pip');
$phar->setSignatureAlgorithm(Phar::SHA1);

$phar->startBuffering();

$files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(__DIR__.'/vendor/pip', FilesystemIterator::CURRENT_AS_FILEINFO | FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
foreach ($files as $file) {
    if (false !== strpos($file->getRealPath(), '.git')) {
        continue;
    }

    $path = str_replace(realpath(__DIR__).'/', '', $file->getRealPath());
    $phar->addFile($file->getRealPath(), $path);

    echo "$path\n";
}

$phar->addFile('server.php');

$phar->setDefaultStub('server.php', 'server.php');

$phar->stopBuffering();
$phar->compressFiles(Phar::GZ);

unset($phar);
